server:
  port: 8080

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      url: http://localhost:8088
    client:
      prefer-ip: true
  application:
    name: web ui
endpoints:
  shutdown:
    enabled: true
    sensitive: false

zuul:
  routes:
    hello:
      url: http://localhost:8081/hello
    world:
      url: http://localhost:8082/world


ribbon:
  eureka:
    enabled: false