server:
  port: 8081

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      url: http://localhost:8088
    client:
      prefer-ip: true
  application:
    name: hello service

endpoints:
  shutdown:
    enabled: true
    sensitive: false

world-service:
  url: http://localhost:8082/