server:
  port: 8082


management:
  security:
    enabled: false

spring:
  boot:
    admin:
      url: http://localhost:8088
    client:
      prefer-ip: true
  application:
    name: world service

endpoints:
  shutdown:
    enabled: true
    sensitive: false
